### ISSUE TITLE
Validate Password recovery

### ISSUE THREAD

**Issue by mauleyzaola** [mauleyzaola/raiders-cashflow#29]
Please make sure everything works as intended in #28 
When you're done if it was ok, add the label ```verified``` to this issue and close

**Comment by mauleyzaola2** [comment]
*no it is not working fine at all*

**Comment by mauleyzaola** [comment]
Why? I tested it before and it was good
What is happening?

**Comment by mauleyzaola2** [comment]
i click it and it does not recognize my mail, so it doesn't give my password

**Comment by mauleyzaola** [comment]
You're right I missed the '2' in your email address. Please try again,
should work now.

**Comment by mauleyzaola2** [comment]
ok

**Comment by mauleyzaola2** [comment]
no it does not work
![image](https://cloud.githubusercontent.com/assets/13241907/10352206/558cec06-6d13-11e5-8b35-08a9c656d608.png)

![image](https://cloud.githubusercontent.com/assets/13241907/10352237/8d390356-6d13-11e5-8154-6bb06ac0162e.png)

**Comment by mauleyzaola** [comment]
:smile: read carefuly

**Comment by mauleyzaola2** [comment]
sorry my fault its all going well (i need to read more...)
