### ISSUE TITLE
Validate Family and Players are working ok

### ISSUE THREAD

**Issue by mauleyzaola** [mauleyzaola/raiders-cashflow#31]
@ruleyzaola Ru, the work on #24 has been completed but I need you to test it. Here is what you need to do:

1. Create two families (Leyzaola Acevedo and Garces Lopez)
2. Create three players (Diego, Ruben and Mau)
3. Assign the players to the families.
4. Modify some information like date of birth and check changes are being applied
5. Remove some player
6. Open the families and see their players on the screen

When you're done testing please remove the ```testing``` label from this issue and add the ```verified``` label, so we can know this has been tested by you.

**Comment by ruleyzaola** [comment]
ready ,i make a screenshot?

**Comment by mauleyzaola** [comment]
always add some evidence of your work please :smile:

**Comment by ruleyzaola** [comment]
ok

**Comment by ruleyzaola** [comment]
![image](https://cloud.githubusercontent.com/assets/13224219/10323711/777fe3aa-6c4a-11e5-8b32-369c4f3423b9.png)

**Comment by ruleyzaola** [comment]
![image](https://cloud.githubusercontent.com/assets/13224219/10323748/b60da5a8-6c4a-11e5-99c5-da50d94622d9.png)

**Comment by ruleyzaola** [comment]
i'ts ok?

**Comment by mauleyzaola** [comment]
add members to the families

**Comment by mauleyzaola** [comment]
Looks good. Just add the label I wrote above please and close this issue.
