### ISSUE TITLE
cuotas

### ISSUE THREAD

**Issue by olguichi** [mauleyzaola/raiders-cashflow#74]
q las cuotas se puedan editar

**Comment by mauleyzaola** [comment]
Permitir todas estas opciones:

1. Modificar Importe de un documento por cobrar. Si ya tiene saldo evitar que el importe sea mayor a la suma de sus pagos

2. Eliminar un documento por cobrar. Siempre que no tenga cobranza aplicada

3. Agregar un nuevo documento por cobrar. Unicamente validar que la fecha no exista en otro documento del mismo jugador. Recalcular los saldos hacia arriba (jugador, categoria, temporada)

**Comment by mauleyzaola** [comment]
PR: #81
